/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#f7f9fb",
        "surface-dim": "#d8dadc",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f6",
        "surface-container": "#eceef0",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "on-surface": "#191c1e",
        "on-surface-variant": "#3f4850",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f3",
        "outline": "#707881",
        "outline-variant": "#bfc7d2",
        "surface-tint": "#006398",
        "primary": "#006194",
        "on-primary": "#ffffff",
        "primary-container": "#007bb9",
        "on-primary-container": "#fdfcff",
        "inverse-primary": "#93ccff",
        "secondary": "#565e74",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "tertiary": "#006947",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00855b",
        "on-tertiary-container": "#f5fff6",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#cce5ff",
        "primary-fixed-dim": "#93ccff",
        "on-primary-fixed": "#001d31",
        "on-primary-fixed-variant": "#004b73",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        "background": "#f7f9fb",
        "on-background": "#191c1e",
        "surface-variant": "#e0e3e5",
        "brand": {
          "dark": "#0F172A",
          "primary": "#0284C7",
          "accent": "#38BDF8",
          "light": "#F0F9FF",
          "wa": "#25D366",
          "waDark": "#1EBE5D"
        },
        "sky": {
          50: "#f0f9ff",
          100: "#e0f2fe",
          200: "#bae6fd",
          300: "#7dd3fc",
          400: "#38bdf8",
          500: "#0ea5e9",
          600: "#0284c7",
          700: "#0369a1",
          800: "#075985",
          900: "#0c4a6e"
        },
        "cyan": {
          50: "#ecfeff",
          100: "#cffafe",
          200: "#a5f3fc",
          300: "#67e8f9",
          400: "#22d3ee",
          500: "#06b6d4",
          600: "#0891b2",
          700: "#0e7490",
          800: "#155e75",
          900: "#164e63"
        }
      },
      spacing: {
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "margin": "2.5rem",
        "margin-mobile": "1.25rem",
        "gutter-mobile": "1rem",
        "gutter": "1.5rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "sans": ["Plus Jakarta Sans", "Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "title": ["Plus Jakarta Sans", "sans-serif"],
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-mobile": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "title": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "56px", fontWeight: "800" }],
        "headline-sm": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "headline-lg": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "700" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "22px", fontWeight: "400" }],
        "display-mobile": ["32px", { lineHeight: "40px", fontWeight: "800" }]
      }
    }
  },
  plugins: [],
}
